baseURL: https://www.brbtechsolutions.com/
languageCode: en-us
title: BRB Tech Solutions
theme: "PaperMod"
# Sample config: https://github.com/adityatelange/hugo-PaperMod/wiki/Installation


params:
  title: BRB Tech Solutions
  author: Brett Barker
  defaultTheme: dark
  disableThemeToggle: true
  env: production
  
  custom_css: 
    - css/custom.css

  profileMode:
    enabled: true
    title: "BRB Tech Solutions"
    subtitle: Solving Your Technology Problems
    buttons:
      - name: About Us
        url: "/about"
      - name: Contact Us
        url: "/contact"

  socialIcons:
    # - name: email
    #   url: mailto:brett.barker@brbtechsolutions.com
    - name: github
      url: https://github.com/brettrbarker/
  
menu:
  main:
    - identifier: about
      name: About Us
      url: /about/
      weight: 10
    - identifier: contact
      name: Contact Us
      url: /contact/
      weight: 20